In [1]:
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
#Ejercicio 1
tabla1 = np.array([
    [85, 65],
    [50, 100]
])

# Prueba Chi-cuadrada
chi2, p, dof, expected = chi2_contingency(tabla1)

print("\nTabla observada:\n", tabla1)
print("\nFrecuencias esperadas:\n", expected)
print("\nChi-cuadrada:", chi2)
print("Grados de libertad:", dof)
print("p-valor:", p)

# Interpretación
alpha = 0.05
if p < alpha:
    print("\nConclusión: Existe relación significativa entre ciudad y transporte")
else:
    print("\nConclusión: No existe relación significativa")


Tabla observada:
 [[ 85  65]
 [ 50 100]]

Frecuencias esperadas:
 [[67.5 82.5]
 [67.5 82.5]]

Chi-cuadrada: 15.569023569023571
Grados de libertad: 1
p-valor: 7.954719446253618e-05

Conclusión: Existe relación significativa entre ciudad y transporte


In [3]:
#Ejercico 2

tabla2 = np.array([
    [40, 20],
    [35, 45],
    [15, 45]
])

chi2, p, dof, expected = chi2_contingency(tabla2)

print("\nTabla observada:\n", tabla2)
print("\nFrecuencias esperadas:\n", expected)
print("\nChi-cuadrada:", chi2)
print("Grados de libertad:", dof)
print("p-valor:", p)

if p < alpha:
    print("\nConclusión: Existe relación entre nivel educativo y fumar")
else:
    print("\nConclusión: No existe relación")


Tabla observada:
 [[40 20]
 [35 45]
 [15 45]]

Frecuencias esperadas:
 [[27. 33.]
 [36. 44.]
 [27. 33.]]

Chi-cuadrada: 21.127946127946128
Grados de libertad: 2
p-valor: 2.583002290820995e-05

Conclusión: Existe relación entre nivel educativo y fumar


In [4]:
#Ejercicio 3

tabla3 = np.array([
    [10, 50],
    [30, 40],
    [45, 5]
])

chi2, p, dof, expected = chi2_contingency(tabla3)

print("\nTabla observada:\n", tabla3)
print("\nFrecuencias esperadas:\n", expected)
print("\nChi-cuadrada:", chi2)
print("Grados de libertad:", dof)
print("p-valor:", p)

if p < alpha:
    print("\nConclusión: Existe relación entre dieta y colesterol")
else:
    print("\nConclusión: No existe relación")


Tabla observada:
 [[10 50]
 [30 40]
 [45  5]]

Frecuencias esperadas:
 [[28.33333333 31.66666667]
 [33.05555556 36.94444444]
 [23.61111111 26.38888889]]

Chi-cuadrada: 59.72401592215833
Grados de libertad: 2
p-valor: 1.0742236856774164e-13

Conclusión: Existe relación entre dieta y colesterol
